### PR TITLE
fixed incorrect or redundant mappings for devnagri transliteration

### PR DESCRIPTION
**Pull request by irvanjitsingh**
Removed redundant mappings for common punctuation characters (i.e. "!", "?") that were causing the devnagri transliteration to break.

### CODE REVIEW

**Comment by gursevaksevadar** [comment]
Commits by @gursevaksevadar and @irvanjitingh should have been two seperate issues/protocols.

**Review by bogas04 — APPROVED** [review]

**Review by tarunsingh5 — COMMENTED** [review]
the comment you left suggests that you are repeating the original char - but the actual tests dont show that

in particular: "(original char)+(halant)+(original char)"

**Comment by irvanjitsingh** [comment]
@tarunsingh5  explanation for adhik fix:
ਅੱਲਖ: A`lK or A~lK (a-lakh) becomes अँलख; it should be अल्लख

the unicode combination for ल्ल is char+halant+char; to acheive this in the code:
1) for every instance of  (halant ascii)+ (lowercase L), repeat the character once : (h)(l)(h)(l)
2) remove the first halant ascii char: (l)(h)(l)
3) unicode conversion should result in ल्ल

**Comment by irvanjitsingh** [comment]
bindi's still need to be fixed; will defer to @gursevaksevadar for further explanations

**Pull request merged**
