### PR TITLE
Correct handling of supplementary letters

### LINKED ISSUE #92: Potential bug when converting a "ਸ਼" with sihaari
ਵਾਹਿਗੁਰੂਜੀਕਾਖਾਲਸਾਵਾਹਿਗੁਰੂਜੀਕੀਫਤੇ

I noticed a couple of times when I was previewing words like: "ਪੋਸ਼ਿਸ਼" or "ਬਖਸ਼ਿਸ਼" the Gurmukhi script (the English conversion) would be a little off. 

Take this example:
 
```javascript
anv.unicode('ਸ਼', true); // expects sæ
anv.unicode('ਸ਼ਿ', true); // expects "isæ"
anv.unicode('ਸ਼ਿਸ਼', true); // expects "isæsæ"
```

But the results are different. Check it out: 

Screen Shot 2020-09-20 at 9 58 55 AM

Here is what "ਪੋਸ਼ਿਸ਼" looks like when incorrectly converted using `anv.unicide('ਪੋਸ਼ਿਸ਼"', true);`. The image below is being displayed with the `OpenGurbaniAkhar-Regular.otf` font.

Screen Shot 2020-09-20 at 9 59 52 AM

**I've only seen this happen with the Sihaari,** other vowels are looking good. 

Screen Shot 2020-09-20 at 10 21 40 AM

### PR DESCRIPTION
**Pull request by hamsbrar**
This pull request fixes #92

### CODE REVIEW

**Comment by irvanjitsingh** [comment]
@hamsbrar thanks for putting this in, taking a look now!

**Review by irvanjitsingh — DISMISSED** [review]
lgtm, your are failing with the linter though; could you run `yarn test --fix? thanks!

**Comment by hamsbrar** [comment]
@irvanjitsingh Thanks for letting me know. I've pushed some fixes.

PS: It's possible that the warnings are not related to the changes I made or my linter is mis-configured.

**Review by irvanjitsingh — APPROVED** [review]
lgtm

**Pull request merged**
