### PR TITLE
Fixes issues in devnagri

### PR DESCRIPTION
**Pull request by Gauravjeetsingh**
Fixes the issues pointed in #35 

Fixes so far are highlighted with Green outline.
fixed

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
Recent commit adds following two fixes:

screenshot from 2019-02-08 18-15-04

**Comment by tarunsingh5** [comment]
@Gauravjeetsingh is this still a WIP?

**Comment by Gauravjeetsingh** [comment]
@tarunsingh5 As suggested in slack, we need devnagri rules just like we have in english.js
Those can be added in a separate pull request.

This pull request fixes a few typos I found in japji sahib and sukhmani sahib.

**Comment by tarunsingh5** [comment]
going to approve this and merge

**Review by tarunsingh5 — APPROVED** [review]

**Pull request merged**
